### PR TITLE
Make typescript definitions work

### PR DESCRIPTION
**Pull request by roblav96**
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package
Incredible good work on this!!! =]

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
typescript definitions dont work

## What is the new behavior?
now they do

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Viatorus** [comment]
Thank you for. :) And thank you for the hint, how to publish typescript definitions.

I think this is the wrong package.json to change this. This is a monorepro so all package.json in the directory packages/**/... have to be changed - right?

**Comment by roblav96** [comment]
@Viatorus Only the root `package.json` file needs to be modified =]

**Comment by Viatorus** [comment]
@roblav96 Could you please check out the newest release (2.0.0-beta.5).
Typings should know be enabled.

**Comment by roblav96** [comment]
@Viatorus This PR was never merged with `2.0.0-beta.5`, so the typings still don't work :/

**Comment by roblav96** [comment]
@Viatorus You should review the [TypeScript Publishing Guidelines](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) and read [How to create strongly-typed npm packages](https://medium.com/@mweststrate/how-to-create-strongly-typed-npm-modules-1e1bda23a7f4) before you publish a stable build. Feel free to email me if you need help =]

**Comment by Viatorus** [comment]
@roblav96 Did you try it out? For me, it works.

This is a mono repository. The root package.json will never be published. Instead the package.json 
for each package in the directory 'packages/*/' will be published to npm.

If you run `npm install @lokijs/loki|` the file: *packages/loki/package.json* will be installed. This files contains the needed entry for Typescript.


P.S. Coveralls is a bot. ;)

**Comment by roblav96** [comment]
@Viatorus lmao I guess I scrolled through that too quick lol I'll try this again,

**Comment by Viatorus** [comment]
Should work already. If not, please reopen.

**Pull request closed without merging**
